name: machina
favicon: null
layout_spectrum: 0.93804
typography_spectrum: 0.60311
title: Jimmy Thanki
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3e3e3e'
    - '#b9b9b9'
    - '#8c1517'
  brandStrength: 0.625
  lightness: 0.48305635596625507
  saturation: 0.9540062341839075
  rhythmicContrast: 0.48077159258536994
purpose: []
